### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by kushbushcrits** [twitchdev/extension-hello-world#6]
Number 6 does not exist................ 

![001](https://user-images.githubusercontent.com/50747078/57939894-21385e00-7880-11e9-9de3-96faf8fca14d.png)
![002](https://user-images.githubusercontent.com/50747078/57939910-285f6c00-7880-11e9-83b7-1e781ea475b5.png)

**Comment by BlaineCan** [comment]
On Readme.md, click on the link Developer Dashboard under Setup list item number 2. That will redirect you to dev.twitch.tv/console/extensions. Under Console, the tab on the far left is titled Overview. That should be what you're looking for. Hope this helps.

**Comment by mauerbac** [comment]
Thanks @Whatchamazog
